dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - pip install tinydownload
  - pip install codecov
  - pip install pytest-cov
addons:
  apt:
    packages:
      - automake
      - autoconf
      - build-essential
      - libass-dev
      - libfreetype6-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libfdk-aac-dev
      - pkg-config
      - texinfo
      - zlib1g-dev
      - yasm
      - nasm
      - libmp3lame-dev
      - libav-tools
install:
  - pip install -r requirements.txt
  - tinydownload 05861434675432854607 -o ~/bin/ffmpeg
  - chmod 755 ~/bin/ffmpeg
script: python -m pytest test --cov=.
after_success: codecov
