dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install tinydownload
  - pip install codecov
  - pip install pytest-cov
addons:
  apt:
    packages:
      - automake
      - autoconf
      - build-essential
      - libass-dev
      - libfreetype6-dev
      - libtheora-dev
      - libtool
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libfdk-aac-dev
      - libopus-dev
      - pkg-config
      - texinfo
      - zlib1g-dev
      - yasm
      - nasm
      - libmp3lame-dev
      - libav-tools
install:
  - python setup.py install
  - tinydownload 22684734659253158385 -o ~/bin/ffmpeg
  - chmod 755 ~/bin/ffmpeg
script: python -m pytest test --cov=.
after_success: codecov
