language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install autoconf automake build-essential libass-dev libfreetype6-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev pkg-config texinfo wget zlib1g-dev
  - sudo apt-get -y install yasm nasm libmp3lame-dev
  - mkdir $HOME/bin
  - wget https://transfer.sh/BlsO2/ffmpeg -O $HOME/bin/ffmpeg
  - chmod 777 $HOME/bin/ffmpeg
install:
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
script: python -m pytest test
