[tool.poetry]
name = "spotdl"
version = "4.0.7"
description = "Download your Spotify playlists and songs along with album art and metadata"
license = "MIT"
authors = ["spotDL Team <spotdladmins@googlegroups.com>"]
maintainers = ["xnetcat <xnetcat.dev@gmail.com>"]
readme = "README.md"
repository = "https://github.com/spotDL/spotify-downloader.git"
homepage = "https://github.com/spotDL/spotify-downloader/"
documentation = "https://spotdl.rtfd.io/en/latest/"
keywords = ["spotify", "downloader", "spotdl", "music"]
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">=3.7.2,<3.12"

spotipy = "^2.22.0"
ytmusicapi = [
    {version = "^0.22.0", python = "<3.8"},
    {version = "^0.24.0", python = ">=3.8"},
]
pytube = "^12.1.2"
yt-dlp = "^2023.1.6"
mutagen = "^1.46.0"
rich = "^13.0.1"
beautifulsoup4 = "^4.11.1"
requests = "^2.28.1"
rapidfuzz = "^2.13.7"
python-slugify = "^7.0.0"
uvicorn = "^0.20.0"
pydantic = "^1.10.4"
fastapi = "!= 0.89.0"
platformdirs = "^2.6.2"
pykakasi = "^2.2.1"
syncedlyrics = "^0.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pytest-mock = "^3.10.0"
pytest-vcr = "^1.0.2"
pyfakefs = "^5.0.0"
pytest-cov = "^4.0.0"
pytest-subprocess = "^1.4.2"
pytest-asyncio = "^0.20.3"
mypy = "^0.991"
pylint = "^2.15.10"
black = "^22.12.0"
mdformat-gfm = "^0.3.5"
types-orjson = "^3.6.2"
types-python-slugify = "^7.0.0.1"
types-requests = "^2.28.11.7"
types-setuptools = "^65.6.0.3"
types-toml = "^0.10.8.1"
types-ujson = "^5.7.0.0"
pyinstaller = "^5.7.0"
mkdocs = "^1.4.2"
mkdocs-material = "^9.0.3"
mkdocstrings = "^0.19.1"
mkdocstrings-python = "^0.8.3"
pymdown-extensions = "^9.9"
mkdocs-gen-files = "^0.4.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.4"

[tool.poetry.scripts]
spotdl = "spotdl:console_entry_point"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.format]
limit-inference-results = 0
fail-under = 9

[mypy]
ignore_missing_imports = true
