[tool.poetry]
name = "spotdl"
version = "4.2.4"
description = "Download your Spotify playlists and songs along with album art and metadata"
license = "MIT"
authors = ["spotDL Team <spotdladmins@googlegroups.com>"]
maintainers = ["xnetcat <xnetcat.dev@gmail.com>"]
readme = "README.md"
repository = "https://github.com/spotDL/spotify-downloader.git"
homepage = "https://github.com/spotDL/spotify-downloader/"
documentation = "https://spotdl.rtfd.io/en/latest/"
keywords = ["spotify", "downloader", "spotdl", "music"]
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.13"

spotipy = "^2.23.0"
ytmusicapi = "^1.3.2"
pytube = "^15.0.0"
yt-dlp = "^2023.11.16"
mutagen = "^1.47.0"
rich = "^13.7.0"
beautifulsoup4 = "^4.12.2"
requests = "^2.31.0"
rapidfuzz = "^3.5.2"
python-slugify = {extras = ["unidecode"], version = "^8.0.1"}
uvicorn = "^0.23.2"
pydantic = "^2.5.2"
fastapi = "^0.103.0"
platformdirs = "^3.11.0"
pykakasi = "^2.2.1"
syncedlyrics = "^0.7.0"
soundcloud-v2 = "^1.3.1"
setuptools = "^69.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-mock = "^3.12.0"
pytest-vcr = "^1.0.2"
pyfakefs = "^5.3.2"
pytest-cov = "^4.1.0"
pytest-subprocess = "^1.5.0"
pytest-asyncio = "^0.21.1"
mypy = "^1.7.1"
pylint = "^3.0.2"
black = "^23.11.0"
mdformat-gfm = "^0.3.5"
types-orjson = "^3.6.2"
types-python-slugify = "^8.0.0.3"
types-requests = "==2.31.0.6"
types-setuptools = "^69.0.0.0"
types-toml = "^0.10.8.7"
types-ujson = "^5.8.0.1"
pyinstaller = "^6.2.0"
mkdocs = "^1.5.3"
isort = "^5.12.0"
dill = "^0.3.7"
mkdocs-material = "^9.4.14"
mkdocstrings = "^0.22.0"
mkdocstrings-python = "^1.7.5"
pymdown-extensions = "^10.5"
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.5"
vcrpy = "^5.1.0"

[tool.poetry.scripts]
spotdl = "spotdl:console_entry_point"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.format]
limit-inference-results = 0
fail-under = 9

[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
    "vcr",
]
